### ISSUE TITLE
client-secret artik gecerli degil

### ISSUE THREAD

**Issue by suchcodemuchwow** [e4c6/eksi_unofficial_api#4]
```
curl --location --request POST 'https://api.eksisozluk.com/Token' \
--header 'Accept: application/json' \
--header 'Accept-Encoding: gzip' \
--header 'Content-Type: application/json' \
--data-raw '{
    "grant_type": "password",
    "username": "",
    "password": "",
    "client_secret": "badf7656-e4ff-46a9-a610-099cdd734066",
    "api_secret": "68f779c5-4d39-411a-bd12-cbcc50dc83dd",
}'
```

[118328919](https://eksisozluk.com/entry/118328919) Entryden yola cikarak bu request i farkli sekillerde denedim (token,Token, api_secretli/siz) ama malesef invalid_client cevabi aliyorum. Dokumantasyonu guncelleme sansimiz var mi acaba ? Decompile etme process'i cok zahmetli ve bilmedigim bi alana surukluyor. 

Ayrica eger su konuda bilgi sahibiysen ve aydinlatirsan cok tatli olur. Iphoneda fiddler mitm kullanarak request'i intercept etmeye calismistim bu dokumantasyonu bulmadan once. Diger buyuk (tinder, gmail vs) uygulamalarda https trafigini yakalarken (facebook,instagram ve eksisozlukte) internet baglanti hatasi aliyorum sebebini de bir turlu cozemedim.

**Comment by e4c6** [comment]
Güncel ekşi uygulamasında certificate pinning var. Bu yüzden requestleri yakalayamıyor olabilirsin. Eski sürümlere downgrade edersen belki işini görebilir. 

v2 ile birlikte güncellemeyi yapacağım, bu arada çok vakit bulamadım.
